# Generated by Django 2.2.7 on 2019-11-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_auto_20191106_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
